# Generated by Django 2.2.7 on 2019-11-07 14:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bread', '0002_auto_20191106_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='contacts',
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default=django.utils.timezone.now, max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
