# Generated by Django 2.2.7 on 2019-11-07 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bread', '0003_auto_20191107_1430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='zipcode',
        ),
    ]
