# Generated by Django 2.2.7 on 2019-11-07 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bread', '0004_remove_order_zipcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='post',
        ),
    ]
